config/routes.rb
Travees::Application.routes.draw do

  get "search_location/:query_string", to: 'itinerary#search', as: 'search_location'
  resources :itinerary

  get "home", to: 'home#index', as: 'home'
  
  namespace :auth do
    get "sign_up", to: 'register#index', as: 'sign_up'
    match "process_signup", to: 'register#create', via: :post

    get "sign_in", to: 'signin#index', as: 'sign_in'
    match "sign_out", to: 'signin#destroy', via: :delete
    match "process_signin", to: 'signin#create', via: :post
  end

  root 'landing#index'

  
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :username, presence: true, length: { minimum: 3, maximum: 20 }, uniqueness: true
	validates :fullname, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/ }
	validates :password, confirmation: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	validates :agreement, acceptance: { accept: 'yes' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	user_signed_in
  end
end

app/controllers/itinerary_controller.rb
class ItineraryController < ApplicationController
  def index
  end

  def new
    user_signed_in
  end

  def search
    @places = Geocoder.search(params[:query_string])
    render json: @places
  end

  def show
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# saving the user into session
	def sign_in(user_id, username)
		session[:user_id]  = user_id
		session[:username] = username
	end

	#check if the user has been signed in
	def user_signed_in
		@user_id  = session[:user_id]
		@username = session[:username]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itinerary_helper.rb
module ItineraryHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/itinerary/create.html.erb
<h1>Itinerary#create</h1>
<p>Find me in app/views/itinerary/create.html.erb</p>

app/views/itinerary/destroy.html.erb
<h1>Itinerary#destroy</h1>
<p>Find me in app/views/itinerary/destroy.html.erb</p>

app/views/itinerary/edit.html.erb
<h1>Itinerary#edit</h1>
<p>Find me in app/views/itinerary/edit.html.erb</p>

app/views/itinerary/show.html.erb
<h1>Itinerary#show</h1>
<p>Find me in app/views/itinerary/show.html.erb</p>

app/views/itinerary/update.html.erb
<h1>Itinerary#update</h1>
<p>Find me in app/views/itinerary/update.html.erb</p>

app/views/landing/index.html.erb
<div id="pitch" class="wrap-outer">
	<div class="wrap">
		<div class="row" id="pitch">
			<h2 class="title">Find <span class="variable object">Things</span> To Do in <span class="variable location">Bali</span></h2>
			<h3 class="description">Share and search iteneraries.Try it out try! Click and change these.</h3>
		</div>
	</div><!-- .wrap -->
</div><!-- #pitch.wrap-outer -->

<div id="showcase" class="wrap-outer">
	<div class="wrap">
		<div class="row">
			<div id="cards">
				<% for i in 0..8 %>
				<div class="card">
					<div class="content">
						<p>Try the best burger in town: @burgeRocksID FTW!</p>
					</div>
					<div class="meta">
						<div class="author">
							<a href="#" class="avatar circle"><img src="/assets/static/avatar-30.jpg" alt="" class="circle"></a>
							<a href="#" class="name">Clark Khan</a>
						</div><!-- .author -->
						<ul class="actions">
							<li><a href="#" class="discuss"><span class="icon"></span><span class="popup">+</span></a></li>
							<li><a href="#" class="done"><span class="icon"></span><span class="popup">32</span></a></li>
							<li><a href="#" class="want"><span class="icon"></span><span class="popup">69</span></a></li>
							<li><a href="#" class="more"><span class="icon"></span><span class="popup">+</span></a></li>
						</ul>
					</div><!-- .meta -->
				</div><!-- .card -->
				<% end %>
			</div><!-- #cards -->
			<div id="more-cards">
				<a href="#" class="button">Load More To-Dos</a>
			</div>
		</div>			
	</div><!-- .wrap -->
</div><!-- #showcase.wrap-outer -->

<div id="stories" class="wrap-outer">
	<div class="wrap">
		<div class="row">
			<div class="column one-third">
				<div class="story">
					<img src="/assets/static/thumb-250.jpg" alt="" class="circle">
					<h2 class="title">Travees: From and For Travellers</h2>
					<div class="description">
						<p>We love to travel. We want to know what to do in our destination.  We love to share our travelling story.  That's why we built Travees.</p>
					</div>
				</div>
			</div><!-- .column.one-third -->
			<div class="column one-third">
				<div class="story">
					<img src="/assets/static/thumb-250.jpg" alt="" class="circle">
					<h2 class="title">Find What To Do Here And There</h2>
					<div class="description">
						<p>Travelling to places you haven't gone before? Find what to do, places to stay, etc from iteneraries made by fellow locals and travellers.</p>
					</div>
				</div>
			</div><!-- .column.one-third -->
			<div class="column one-third last">
				<div class="story">
					<img src="/assets/static/thumb-250.jpg" alt="" class="circle">
					<h2 class="title">Tell People What To Do Here And There</h2>
					<div class="description">
						<p>Whether you've just travelled to that exotic places or you're a local in your city, share your itenerary and top-things to do in certain places</p>
					</div>
				</div>
			</div><!-- .column.one-third.last -->
		</div>			
	</div>
</div><!-- #stories.wrap-outer -->

<div id="bottom-cta" class="wrap-outer">
	<div class="row">
		<div id="bottom-pitch">
			<p>You're gonna love <span class="travees">Travees</span></p> 
		</div>
		<a href="#" id="cta" class="button danger">Sign Up Now</a>
	</div>		
</div><!-- #bottom-cta.wrap-outer -->

<div id="cover-background">
	<img src="/assets/static/cover.jpg" alt="">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>TRAVEES - Social Itenerary Platform</title>
  	
    <!-- CSS -->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <!--[if lte IE 8]>
        <%= stylesheet_link_tag    "mapbox.ie" %>
    <![endif]-->
    
    <!-- JS -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!-- ICONS -->
    <link rel="Shortcut Icon" href="/assets/icons/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/icons/apple-touch-icon-144x144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/icons/apple-touch-icon-precomposed.png">    
    
    <%= csrf_meta_tags %>
</head>
<body>
	<div id="top-navigation" class="wrap-outer">
		<div class="wrap">
	    	<div class="row">
	        	<h1 id="site-name"><a href="TRAVEES - Social Itenerary Platform" title="">TRAVEES</a></h1>

                <% if @user_id.nil? %>
	        	<ul id="sign-form-nav">
	            	<li><a href="<%= auth_sign_in_path %>" class="signin">Sign In</a></li>
	            	<li><a href="<%= auth_sign_up_path %>" class="button">Sign Up</a></li>
	        	</ul>
                <% else %>
                <ul id="top-menu">
                    <li id="top-menu-search">
                        <a href="#">
                            <span class="icon"></span>
                        </a>
                    </li>
                    <li id="top-menu-new">
                        <a href="#">
                            <span class="icon"></span>
                        </a>
                    </li>
                    <li id="top-menu-user">
                        <a href="#">
                            <span class="icon"></span>
                        </a>
                    </li>
                    <li id="top-menu-settings">
                        <a href="#">
                            <span class="icon"></span>
                        </a>
                    </li>
                    <li>
                        <%= link_to "Sign Out", auth_sign_out_path, method: :delete %>
                    </li>
                </ul><!-- #top-menu -->
                <% end %>
	    	</div><!-- .row -->
		</div>
	</div>

	<%= yield %>

    <div id="footer" class="wrap-outer">
        <div class="wrap">
            <div id="footer-menu">
                &copy; <a href="">PT. Travees Media</a> &bull;  <a href="">About Travees</a> &bull; <a href="">Support</a> &bull; <a href="">Jobs</a> &bull; <a href="">Term of Service</a> &bull; <a href="">Privacy Policy</a>
            </div>
        </div>        
    </div>
</body>
</html>

app/views/shared/_facebook.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '616579641712933',                        // App ID from the app dashboard
      channelUrl : '//0.0.0.0:3000/channel.html', // Channel file for x-domain comms
      status     : true,                                 // Check Facebook Login status
      xfbml      : true                                 // Look for social plugins on the page
    });

    // Check if the user has login or not
    FB.Event.subscribe('auth.authResponseChange', function(response) {
      console.log(response);
      if(response.status === 'connected') {
        FB.api('/me', function(res) {
          $('#username').val(res.username);
          $('#email').val(res.email);
          $('#fullname').val(res.name);
        });
      }
    });

    // click the login button
    $('#signin-facebook').click(function() {
      FB.login(function(response) {
        
      }, {scope: 'email, user_about_me, publish_stream'});
      return false;
    });
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>